// <auto-generated />
using MVC2AT.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC2AT.Data.Migrations
{
    [DbContext(typeof(EstadoContext))]
    [Migration("20200617001841_RecreateEstadoDB")]
    partial class RecreateEstadoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC2AT.Dominio.Model.Entity.CidadeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("População")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoEntityId");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("MVC2AT.Dominio.Model.Entity.EstadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("População")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Capital")
                        .IsUnique()
                        .HasFilter("[Capital] IS NOT NULL");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("MVC2AT.Dominio.Model.Entity.CidadeEntity", b =>
                {
                    b.HasOne("MVC2AT.Dominio.Model.Entity.EstadoEntity", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
